// <auto-generated />
using System;
using DataPersistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControllerResfulAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318162312_IntitialCreate")]
    partial class IntitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ControllerResfulAPI.models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("deciaml(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d5f08e-3d68-4ef8-8fb4-f0ca1a53ed01"),
                            Name = "Wireless Mouse",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = new Guid("65f52a7a-5ed5-4e70-a3f1-94327453d6c8"),
                            Name = "Mechanical Keyboard",
                            Price = 79.50m
                        },
                        new
                        {
                            Id = new Guid("6d35f2f3-e2f6-417e-97e8-3f7a56eb0f3f"),
                            Name = "USB-C Hub",
                            Price = 39.00m
                        },
                        new
                        {
                            Id = new Guid("ce6e0a8e-fad0-4f17-9c4a-908f4f4c8b95"),
                            Name = "Noise-Canceling Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("4b9e4458-72f9-47d9-9f17-5c65b9fbe11e"),
                            Name = "4K Monitor",
                            Price = 289.00m
                        },
                        new
                        {
                            Id = new Guid("f90285c8-4f71-4554-b757-ad8fb8ea6cc4"),
                            Name = "Laptop Stand",
                            Price = 31.75m
                        },
                        new
                        {
                            Id = new Guid("0f6f8d1e-0fd6-4622-8d85-66f3e95b0e21"),
                            Name = "Webcam 1080p",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("5ea94313-b5ec-44ed-b259-f41ba84f6c5d"),
                            Name = "External SSD 1TB",
                            Price = 109.00m
                        },
                        new
                        {
                            Id = new Guid("31b7c4d1-cb4e-4f61-8fcb-b5e2fc3a6942"),
                            Name = "Ergonomic Chair Cushion",
                            Price = 44.50m
                        },
                        new
                        {
                            Id = new Guid("15f2365e-45cd-48d0-a706-a1b0c6dbf831"),
                            Name = "Portable Bluetooth Speaker",
                            Price = 68.25m
                        },
                        new
                        {
                            Id = new Guid("0a5af839-5b7d-4e95-9418-0f26062734d3"),
                            Name = "Smart LED Desk Lamp",
                            Price = 42.99m
                        },
                        new
                        {
                            Id = new Guid("0ee80519-7c87-4f1b-bf38-15c1a7aa4bb9"),
                            Name = "Wireless Charging Pad",
                            Price = 27.49m
                        },
                        new
                        {
                            Id = new Guid("70ef8a9a-3e8d-4d6b-94ba-7f83d710c3a2"),
                            Name = "Gaming Mouse Pad",
                            Price = 19.95m
                        },
                        new
                        {
                            Id = new Guid("f93aa293-8e10-4fb4-8176-a120744268d1"),
                            Name = "Laptop Cooling Pad",
                            Price = 36.80m
                        },
                        new
                        {
                            Id = new Guid("ff0901f9-a6ac-4f07-8ff6-c82f258c8ad2"),
                            Name = "USB Microphone",
                            Price = 84.20m
                        });
                });

            modelBuilder.Entity("ControllerResfulAPI.models.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5ea5597-90f0-4208-b654-f2cadfc0e801"),
                            ProductId = new Guid("a7d5f08e-3d68-4ef8-8fb4-f0ca1a53ed01"),
                            Reviewer = "Arun",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("df8ab4fc-b59e-430b-91d5-5a54af7af66f"),
                            ProductId = new Guid("a7d5f08e-3d68-4ef8-8fb4-f0ca1a53ed01"),
                            Reviewer = "Maya",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("3ac79f42-6b44-4f96-bf96-0d09008ad68d"),
                            ProductId = new Guid("65f52a7a-5ed5-4e70-a3f1-94327453d6c8"),
                            Reviewer = "Liam",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("7f5f9e5f-d0f3-4d3f-a62f-4d0f9d9601fa"),
                            ProductId = new Guid("65f52a7a-5ed5-4e70-a3f1-94327453d6c8"),
                            Reviewer = "Nora",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("50d5082a-a6af-4dcb-9348-8fe529a9f368"),
                            ProductId = new Guid("6d35f2f3-e2f6-417e-97e8-3f7a56eb0f3f"),
                            Reviewer = "Ava",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("fd248541-7cf8-4a0f-ad2e-d0617f2e9150"),
                            ProductId = new Guid("6d35f2f3-e2f6-417e-97e8-3f7a56eb0f3f"),
                            Reviewer = "Noah",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("29e93c35-e424-4520-a4cf-c2c5f688fef7"),
                            ProductId = new Guid("ce6e0a8e-fad0-4f17-9c4a-908f4f4c8b95"),
                            Reviewer = "Ethan",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("73f26e04-0611-4f30-b435-4afe367c7d4d"),
                            ProductId = new Guid("ce6e0a8e-fad0-4f17-9c4a-908f4f4c8b95"),
                            Reviewer = "Zara",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("9af56d64-244f-4a6e-9ec0-c3e6f51e63ce"),
                            ProductId = new Guid("4b9e4458-72f9-47d9-9f17-5c65b9fbe11e"),
                            Reviewer = "Ivy",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("72659f6a-d102-4d56-8f94-8512497fdb09"),
                            ProductId = new Guid("4b9e4458-72f9-47d9-9f17-5c65b9fbe11e"),
                            Reviewer = "Kai",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("bcfcf25f-6648-4fa8-86fc-5e66fa7208f8"),
                            ProductId = new Guid("f90285c8-4f71-4554-b757-ad8fb8ea6cc4"),
                            Reviewer = "Mila",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("877b7c54-9f48-4e36-8c84-64a36f25c9e3"),
                            ProductId = new Guid("f90285c8-4f71-4554-b757-ad8fb8ea6cc4"),
                            Reviewer = "Omar",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("0c9a381e-c1f4-4854-a49c-03d70c7fd8d2"),
                            ProductId = new Guid("0f6f8d1e-0fd6-4622-8d85-66f3e95b0e21"),
                            Reviewer = "Riya",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("3a7f72c8-a258-4aa9-aa31-df4d508fef74"),
                            ProductId = new Guid("0f6f8d1e-0fd6-4622-8d85-66f3e95b0e21"),
                            Reviewer = "Lucas",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("2f9d2bdf-a412-4f8a-a6d2-c2f823e8dbd8"),
                            ProductId = new Guid("5ea94313-b5ec-44ed-b259-f41ba84f6c5d"),
                            Reviewer = "Anika",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("66ec7be0-29c4-4f5b-af94-8f7b19d99eb8"),
                            ProductId = new Guid("5ea94313-b5ec-44ed-b259-f41ba84f6c5d"),
                            Reviewer = "Eli",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("8f71ec97-2de9-4d2f-8077-7c3985daef3f"),
                            ProductId = new Guid("31b7c4d1-cb4e-4f61-8fcb-b5e2fc3a6942"),
                            Reviewer = "Sofia",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("89a2a08e-53a2-4733-a217-d60eb1f5f315"),
                            ProductId = new Guid("31b7c4d1-cb4e-4f61-8fcb-b5e2fc3a6942"),
                            Reviewer = "Mateo",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("14926b53-52aa-41f8-89d1-43f2f116653f"),
                            ProductId = new Guid("15f2365e-45cd-48d0-a706-a1b0c6dbf831"),
                            Reviewer = "Priya",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("ce2ed848-a6a2-4898-a6ea-15e6740f1a99"),
                            ProductId = new Guid("15f2365e-45cd-48d0-a706-a1b0c6dbf831"),
                            Reviewer = "Jonah",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("6c3ca0b9-5406-4d4f-80f1-f229eb3f66f7"),
                            ProductId = new Guid("0a5af839-5b7d-4e95-9418-0f26062734d3"),
                            Reviewer = "Aiden",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("1c6785fc-6408-4a23-a1ef-2f6403ac6f89"),
                            ProductId = new Guid("0a5af839-5b7d-4e95-9418-0f26062734d3"),
                            Reviewer = "Hana",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("db8f2de4-2ea8-4fef-835b-a63ebce91a90"),
                            ProductId = new Guid("0ee80519-7c87-4f1b-bf38-15c1a7aa4bb9"),
                            Reviewer = "Leo",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a048f2c2-442e-486c-a389-17fbde03477a"),
                            ProductId = new Guid("0ee80519-7c87-4f1b-bf38-15c1a7aa4bb9"),
                            Reviewer = "Emma",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("5771692c-e0f1-4288-b53e-2a81054eecbf"),
                            ProductId = new Guid("70ef8a9a-3e8d-4d6b-94ba-7f83d710c3a2"),
                            Reviewer = "Ben",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("486c43cb-43f5-43f8-87f5-15898f45395d"),
                            ProductId = new Guid("70ef8a9a-3e8d-4d6b-94ba-7f83d710c3a2"),
                            Reviewer = "Sara",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("7f299e6f-a191-4934-99e8-4aa5fd8625d9"),
                            ProductId = new Guid("f93aa293-8e10-4fb4-8176-a120744268d1"),
                            Reviewer = "Iris",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("7601f043-ddf1-4cf1-b5f7-1e3f8dbb6560"),
                            ProductId = new Guid("f93aa293-8e10-4fb4-8176-a120744268d1"),
                            Reviewer = "Victor",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("208d0f06-e713-44fd-bf97-8570eecbf513"),
                            ProductId = new Guid("ff0901f9-a6ac-4f07-8ff6-c82f258c8ad2"),
                            Reviewer = "Nina",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("ed2ad6e4-81ea-4f77-a2a5-fcc9cb4ef7bf"),
                            ProductId = new Guid("ff0901f9-a6ac-4f07-8ff6-c82f258c8ad2"),
                            Reviewer = "Sam",
                            Stars = 4
                        });
                });

            modelBuilder.Entity("ControllerResfulAPI.models.ProductReview", b =>
                {
                    b.HasOne("ControllerResfulAPI.models.Product", null)
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControllerResfulAPI.models.Product", b =>
                {
                    b.Navigation("ProductReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
