// <auto-generated />
using System;
using ActionFilter.Data.AppDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActionFilter.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ActionFilter.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d5f08e-3d68-4ef8-8fb4-f0ca1a53ed01"),
                            Name = "Wireless Mouse",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = new Guid("65f52a7a-5ed5-4e70-a3f1-94327453d6c8"),
                            Name = "Mechanical Keyboard",
                            Price = 79.50m
                        },
                        new
                        {
                            Id = new Guid("6d35f2f3-e2f6-417e-97e8-3f7a56eb0f3f"),
                            Name = "USB-C Hub",
                            Price = 39.00m
                        },
                        new
                        {
                            Id = new Guid("ce6e0a8e-fad0-4f17-9c4a-908f4f4c8b95"),
                            Name = "Noise-Canceling Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("4b9e4458-72f9-47d9-9f17-5c65b9fbe11e"),
                            Name = "4K Monitor",
                            Price = 289.00m
                        },
                        new
                        {
                            Id = new Guid("f90285c8-4f71-4554-b757-ad8fb8ea6cc4"),
                            Name = "Laptop Stand",
                            Price = 31.75m
                        },
                        new
                        {
                            Id = new Guid("d1e5f2a3-8c6b-4e7a-9f8e-2a3b4c5d6e7f"),
                            Name = "External SSD",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = new Guid("e2f6a7b8-9c1d-4f3e-8a7b-5c6d7e8f9a0b"),
                            Name = "Gaming Chair",
                            Price = 199.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
